### ISSUE TITLE
localdatetime es fecha + hora minutos segundos.... seguro quien esto para el cumpleaños? no será mejor un localdate?

### ISSUE THREAD

**Issue by maurociancio** [ariana-salese/DNT-TakeAwayNow#31]
https://github.com/ariana-salese/DNT-TakeAwayNow/blob/50468340cb88f9c11e1bbab68f1c76d8d39c99fc/grails-app/domain/takeawaynow/BeneficiosCumpleanios.groovy#L15

**Comment by LGhosn** [comment]
Solucionado en #47
