### ISSUE TITLE
esto que usan acá creo que ya existe y se llama LocalTime, una hora:minutos sin informacion de dia ni fecha

### ISSUE THREAD

**Issue by maurociancio** [ariana-salese/DNT-TakeAwayNow#41]
https://github.com/ariana-salese/DNT-TakeAwayNow/blob/50468340cb88f9c11e1bbab68f1c76d8d39c99fc/grails-app/domain/takeawaynow/Horario.groovy#L8

**Comment by LGhosn** [comment]
Solucionado en #47
